# Generated by Django 3.2.9 on 2023-09-17 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_department', '0002_alter_department_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='director',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='employee_department.employee'),
        ),
    ]
